---
- name: Setup instances on cloud.
  hosts: localhost
  gather_facts: no
  pre_tasks:
    - name: Get current public ip.
      uri:
        url: http://ipecho.net/plain
        return_content: yes
      register: get_ipecho
    - set_fact:
        my_public_ip: "{{ get_ipecho.content }}"
  roles:
    - role: coreos-k8s-idcf
      group_name: idcf
      firewall_cidr: "{{ my_public_ip }}/32"
      when: coreos_k8s_use_idcf is defined and coreos_k8s_use_idcf
    - role: coreos-k8s-gce
      group_name: gce
      firewall_cidr: "{{ my_public_ip }}/32"
      when: coreos_k8s_use_gce is defined and coreos_k8s_use_gce

- name: CoreOS initial settings.
  hosts: all:!localhost
  gather_facts: no
  sudo: yes
  roles:
    - coreos-pypy

- name: Setup k8s master.
  hosts: coreos-k8s-master
  vars:
    ansible_python_interpreter: /opt/bin/python
  sudo: yes
  roles:
    - coreos-k8s-master

- name: Setup k8s minion.
  hosts: coreos-k8s-minion
  vars:
    ansible_python_interpreter: /opt/bin/python
  sudo: yes
  roles:
    - coreos-k8s-minion
