---
- name: CoreOS initial settings.
  hosts: all
  gather_facts: no
  sudo: yes
  roles:
    - coreos-pypy

- name: Setup k8s master.
  hosts: coreos-k8s-master
  vars:
    ansible_python_interpreter: /opt/bin/python
  sudo: yes
  roles:
    - coreos-k8s-master
