---
- name: systemd daemon-reload
  command: systemctl daemon-reload

- name: restart etcd2
  service:
    name: etcd2.service
    state: restarted

- name: restart fleet
  service:
    name: fleet.service
    state: restarted

- name: restart flanneld
  service:
    name: flanneld.service
    state: restarted

- name: restart kube-proxy
  service:
    name: kube-proxy.service
    state: restarted

- name: restart kube-kubelet
  service:
    name: kube-kubelet.service
    state: restarted
