---
- name: Set cloud-config.yml.
  template:
    src: master.yml
    dest: /opt/cloud-config.yml
  register: set_cloud_config

- name: Run cloudinit.
  command: /usr/bin/coreos-cloudinit -from-file=/opt/cloud-config.yml
  when: set_cloud_config|changed

- name: Start required services.
  service:
    name: "{{ item.name }}"
    state: started
  with_items:
    - name: generate-serviceaccount-key.service
    - name: setup-network-environment.service
    - name: fleet.service
    - name: flanneld.service
    - name: docker.service
    - name: kube-apiserver.service
    - name: kube-controller-manager.service
    - name: kube-scheduler.service
