---
- name: Create drop-in directories.
  file:
    path: /run/systemd/system/{{ item }}.d
    state: directory
  with_items:
    - etcd2.service
    - fleet.service
    - flanneld.service

- name: Set etcd2 drop-in.
  template:
    src: etcd2.30-ansible.conf.j2
    dest: /run/systemd/system/etcd2.service.d/30-ansible.conf
  notify:
    - systemd daemon-reload
    - restart etcd2

- name: Set fleet drop-in.
  template:
    src: fleet.30-ansible.conf.j2
    dest: /run/systemd/system/fleet.service.d/30-ansible.conf
  notify:
    - systemd daemon-reload
    - restart fleet

- name: Set flanneld drop-in.
  template:
    src: flanneld.30-ansible.conf.j2
    dest: /run/systemd/system/flanneld.service.d/30-ansible.conf
  notify:
    - systemd daemon-reload
    - restart flanneld

- name: Set kube-proxy.service unit.
  template:
    src: kube-proxy.service.j2
    dest: /run/systemd/system/kube-proxy.service
  notify:
    - systemd daemon-reload
    - restart kube-proxy

- name: Set kube-kubelet.service unit.
  template:
    src: kube-kubelet.service.j2
    dest: /run/systemd/system/kube-kubelet.service
  notify:
    - systemd daemon-reload
    - restart kube-kubelet

- name: Start required services.
  service:
    name: "{{ item.name }}"
    state: started
    enabled: yes
  with_items:
    - name: etcd2.service
    - name: fleet.service
    - name: flanneld.service
    - name: docker.service
    - name: kube-proxy.service
    - name: kube-kubelet.service
