---
- name: Set cloud-config.yml.
  template:
    src: node.yml
    dest: /opt/cloud-config.yml
  register: set_cloud_config

- name: Run cloudinit.
  command: /usr/bin/coreos-cloudinit -from-file=/opt/cloud-config.yml
  when: set_cloud_config|changed

- name: Start required services.
  service:
    name: "{{ item.name }}"
    state: started
  with_items:
    - name: fleet.service
    - name: flanneld.service
    - name: docker.service
    - name: setup-network-environment.service
    - name: kube-proxy.service
    - name: kube-kubelet.service
